[package]
name = "familytree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3", features=["derive"]}
dioxus = { version = "0.2.4", features = ["desktop"] }
petgraph = "0.6.0"
