name: build

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/**
      - Cargo.toml
      - flake.nix

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check
    - run: nix build .#dockerImage
    - run: ./result | docker load
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: push image
      run: |
        docker tag familytree:latest ghcr.io/sakti/familytree:latest
        docker push ghcr.io/sakti/familytree:latest
